apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "k8s-cd-demo"
  namespace: "default"
  labels:
    app: "k8s-cd-demo"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "k8s-cd-demo"
  template:
    metadata:
      labels:
        app: "k8s-cd-demo"
    spec:
      containers:
      - name: "k8s-cd-demo"
        image: "gcr.io/dark-bindery-284807/k8s-cd-demo:v1"
---        
apiVersion: v1
kind: Service
metadata:
  name: k8s-cd-demo
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: k8s-cd-demo        



